name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Trigger Render deploy
        env:
          RENDER_SERVICE_ID: ${{ secrets.srv-d48k8lchg0os738b55qg }}
          RENDER_API_KEY: ${{ secrets.rnd_NdOLJw3RXaCOMuaGQZOBnC8OphWr }}
        run: |
          echo "Triggering render deploy..."
          curl -X POST \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{"clearCache": true}' \
            https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys
