Write-Host "Run these exact commands locally to push to GitHub (replace <your-repo-url>):"
Write-Host ""
Write-Host "cd 'C:\Users\USER\Desktop\christosphere project'"
Write-Host "git init  # if you haven't already"
Write-Host "git add ."
Write-Host "git commit -m 'Initial commit'"
Write-Host "git branch -M main"
Write-Host "git remote add origin <your-repo-url>"
Write-Host "git push -u origin main"
Write-Host ""
Write-Host "After creating the Render service, set these GitHub secrets in your repo settings (Settings -> Secrets -> Actions):"
Write-Host "RENDER_SERVICE_ID = <the service id from Render>"
Write-Host "RENDER_API_KEY = <your render api key>"
Write-Host ""
Write-Host "Then push to main — GitHub Actions will call Render's deploy API using those secrets."